name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile and link
      run: g++ a.c foo.c -o a.out
    - name: print results
      run: echo "Build COMPLETED"

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: chmod +x ./test-runner.sh
    - name: exec test
      run: ./test-runner.sh
    - name: print results
      run: echo "Test COMPLETED"

